### ISSUE TITLE
npm audit found low severity vulnerabilities in elliptic and jwk-to-pem

### ISSUE THREAD

**Issue by quangdao-itr** [Brightspace/node-jwk-to-pem#191]
Running `npm audit` revealed two low severity vulnerabilities:

* **elliptic package:**
  * Description: Valid ECDSA signatures erroneously rejected. (GHSA-fc9h-whq2-v747)
  * No fix available at this time.
  * Location: node_modules/elliptic
* **jwk-to-pem package:**
  * Description: Depends on a vulnerable version of elliptic.
  * Location: node_modules/jwk-to-pem

**Recommendation:**

It's recommended to monitor these vulnerabilities for updates and potential fixes. Consider upgrading elliptic to a patched version if one becomes available. 

**Additional Information:**

**Comment by RajkiranJogu** [comment]
Hi,
When will this security issue get fixed in `jwk-to-pem` ?

**Comment by quangdao-itr** [comment]
It has been fixed. Thank you!

**Comment by GustavPS** [comment]
> It has been fixed. Thank you!

Is it though? This package still uses elliptic v6.5.7, the fix is included 6.6.0

**Comment by omsmith** [comment]
> When will this security issue get fixed in jwk-to-pem

jwk-to-pem does not deal with signatures, and as such the advisory had no impact on this package.

> Is it though? This package still uses elliptic v6.5.7, the fix is included 6.6.0

^6.5.7 matches 6.6.0. The latest version will be preferred on new installs, and it can be easily updated in application package-locks. Users of Dependabot, as an example, will have received a PR to update elliptic last week.

Will still publish an updated version if that helps some users, likely later today.

You may also want to consider using modern node's built-in features instead of continuing to use jwk-to-pem: https://github.com/Brightspace/node-jwk-to-pem/issues/187#issuecomment-2270577032
