### ISSUE TITLE
CVE-2020-13822 in elliptic : upgrade to 6.5.3

### ISSUE THREAD

**Issue by mleneveut** [Brightspace/node-jwk-to-pem#38]
Hello,

Could you upgrade to elliptic:6.5.3 to fix the CVE-2020-13822 ?

Thanks.

https://github.com/indutny/elliptic/issues/226#issuecomment-646098963

**Comment by j3parker** [comment]
Opps, due to a misconfigured branch protection rule (now fixed) I accidentally added this to `master`: https://github.com/Brightspace/node-jwk-to-pem/commit/e9b706379ea29a2a2be5281561591405780db3c3

Looking into this dependency, just making sure this repo is set up to get version bump PRs automatically first.

**Comment by JacoKoster** [comment]
Is there any news on this? Do you need some help?

**Comment by omsmith** [comment]
So our dependency already floats to 6.5.3. But yes, we can explicitly bump it.

**Comment by omsmith** [comment]
v2.0.4
